--- drivers/input/touchscreen/Makefile
+++ drivers/input/touchscreen/Makefile
@@ -37,11 +37,11 @@
 obj-$(CONFIG_TOUCHSCREEN_S3C2410)	+= s3c2410_ts.o
 obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_3K)       += synaptics_3k.o
 obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_I2C_RMI)	+= synaptics_i2c_rmi.o
-#ifdef ICS_CONFIG
+ifdef CONFIG_ICS
 obj-$(CONFIG_TOUCHSCREEN_ATMEL) += atmel_ics.o
-#else
+else
 obj-$(CONFIG_TOUCHSCREEN_ATMEL) += atmel.o
-#endif
+endif
 obj-$(CONFIG_TOUCHSCREEN_NTRIG) += ntrig.o
 obj-$(CONFIG_TOUCHSCREEN_NTRIG_8x60) += ntrig_8x60.o
 obj-$(CONFIG_TOUCHSCREEN_ELAN_KTF2K)	+= elan_ktf2k.o
